# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a5414d98bec5d9f4030e3093980f493"
name = "Timer Mint"
application_url = "http://h362kcdfqpze9u2ajad7bwrf.91.239.208.85.sslip.io"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "badgebuilderdev.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [ "http://h362kcdfqpze9u2ajad7bwrf.91.239.208.85.sslip.io/api/auth" ]

[app_proxy]
url = "http://h362kcdfqpze9u2ajad7bwrf.91.239.208.85.sslip.io/apps/timer-mint"
subpath = "timer-mint"
prefix = "apps"
